### PR TITLE
1.20.3 & Self hosting

### PR DESCRIPTION
**Pull request by SamB440**
This adds the ability to self-host the resource pack via a local web server and also adds support for 1.20.3. It also fixes various bugs.

~~One problem is the jar size is now massive because of the webserver, I don't know how to fix that.~~

### CODE REVIEW

**Comment by SamB440** [comment]
> You may download and cache the required deps at runtime if needed.

I am not aware of any solutions to do that though. You'd need it both on Spigot and Velocity and all the way back to 1.8.

**Comment by ifacify** [comment]
Use java.net.URLClassLoader

**Comment by SamB440** [comment]
> Download the dependency jar with any http client you prefer to a cache dir and then use java.net.URLClassLoader to load it in so that you don't have to shadow it in your project. You may also read the config first to determine if the jar should be loaded. A lot of plugins (even bengeecord itself) do this trick so you might be able to find some examples.
> 
> Edit: [example](https://github.com/ad1tya2/AdiAuth/blob/master/src/main/java/ad1tya2/adiauth/Bungee/utils/tools.java)

Thanks, using a combination of LuckPerm's URLClassLoaderAccess (which that link uses) and this which I found: https://github.com/Vankka/DependencyDownload, since I wanted hash validation too, it works now.

**Comment by SamB440** [comment]
Tested on 1.20.2 paper server without proxy and 1.20.2 paper server behind proxy. Don't care enough to test other versions, this should be fine to merge now.Tested on 1.20.2 paper server without proxy and 1.20.2 paper server behind proxy. Don't care enough to test other versions, this should be fine to merge now.

Summary of changes:

- Added support for multiple resource packs.
- Added support for per-version resource packs.
- Added the ability to self-host resource packs using a webserver.
- Support for 1.20.2+ players. 1.20.2 is a bad version and will cause multiple resource packs reload, you should update your clients to 1.20.3+.
- 1.20.3+ players will correctly have their resource packs unloaded when reloading on both Spigot and Velocity.
- Dropbox URL validation check now accepts any variant of dl=1, since they keep changing it.
- Fixed player's being kicked if `try-to-stop-fake-accept-hacks` is enabled and `forcepack reload` is used.
- Spigot: Resource pack statuses are now handled asynchronously.
- Spigot: ViaVersion is no longer required to read the client version of a player. This improves support for servers on old versions without viaversion installed.
- Spigot: `prevent-damage` will now work with non-entity sources.
- Velocity: Actions can now be deleted from the config without causing errors.
- Rewritten documentation at https://fortitude.islandearth.net/category/forcepack.
Not in this PR, but for 1.3.0:

- Spigot: Added support for adventure/minimessage. Language files must now use MiniMessage formatting.
- Spigot: Changed the default rejection message to be more descriptive and not link to my old tutorial site. 
- Spigot: `server.properties` is now checked to ensure there is not a resource pack present.

**Comment by Tobias123567** [comment]
global packs are not working anymore on velocity with this pull request

**Comment by SamB440** [comment]
Try the new commit, also send the output of debug mode next time

**Comment by Tobias123567** [comment]
Now it's working again, but when I switch downstream server the pack is always sent again, even though i am in 1.20.4

**Comment by SamB440** [comment]
It seems velocity has not implemented `getAppliedResourcePacks`. I am going to have to track this myself...

**Comment by SamB440** [comment]
Please try the latest commit

**Comment by Tobias123567** [comment]
Yeah thanks, now everything works as intended

**Comment by Tobias123567** [comment]
but now there is a error when joining with 1.20.1 and the pack is not applied too
image

**Comment by SamB440** [comment]
Should be fixed now.

**Comment by SamB440** [comment]
I can't use packetevents on velocity either because it has issues with NBT data when switching worlds.

We have to wait for Velocity to update...

**Comment by SamB440** [comment]
Alright, I've decided to implement it via reflection since the RemoveResourcePack packet class exists on velocity, the method just hasn't implemented it.

Everything should be good now.

**Comment by Tobias123567** [comment]
yeah now everything works

**Pull request merged**
