### PR TITLE
Add Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by CJYKK**

### CODE REVIEW

**Comment by SamB440** [comment]
In the future we should probably add a way for velocity to have translations, but I need to work out a way to do that.

Thanks for your contribution.

**Comment by CJYKK** [comment]
> In the future we should probably add a way for velocity to have translations, but I need to work out a way to do that.
> 
> Thanks for your contribution.

Like .lang file?

**Comment by SamB440** [comment]
> > In the future we should probably add a way for velocity to have translations, but I need to work out a way to do that.
> > Thanks for your contribution.
> 
> Like .lang file?

The problem is we have per-server resource packs which all have their own texts on Velocity, so a simple file like we have on Spigot won't work as that won't be different for each resource pack.

Best idea is probably to have a language file with translation keys such as `servers.example-server.resourcepack.prompt="<yellow>Please accept our resource pack to improve your experience."`.

**Comment by CJYKK** [comment]
I suggest lang files, HOCON or TOML.&nbsp;They are all more in line with your requirements, but it is still up to you to decide.




CJYKK
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SamB440/ForcePack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月27日(星期二) 晚上8:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SamB440/ForcePack] Add Simplified Chinese Translation (PR #13)





   
In the future we should probably add a way for velocity to have translations, but I need to work out a way to do that.
 Thanks for your contribution.
  
Like .lang file?
  
The problem is we have per-server resource packs which all have their own texts on Velocity, so a simple file like we have on Spigot won't work as that won't be different for each resource pack.
 
Best idea is probably to have a language file with translation keys such as servers.example-server.resourcepack.prompt="<yellow&gt;Please accept our resource pack to improve your experience.".

**Pull request merged**
